"""Typed, host-neutral doctest planning and execution."""

from __future__ import annotations

from .contracts import (
    CheckerFactory,
    Contributor,
    DocumentParser,
    ExceptionPolicy,
    ExecutionProfile,
    ExecutionRuntime,
    Provider,
    Registrar,
    Registration,
    RuntimeOutcome,
    RuntimeSettings,
)
from .markup import (
    DoctestDirective,
    MockTabDirective,
    MystDocumentParser,
    RstDocumentParser,
    TestcleanupDirective,
    TestcodeDirective,
    TestoutputDirective,
    TestsetupDirective,
    ensure_directives_registered,
    extract_blocks,
    parse_document,
)
from .model import (
    BlockKind,
    BlockResult,
    Counts,
    Diagnostic,
    Errored,
    ExampleRecipe,
    ExpectedOutput,
    Failed,
    Failure,
    GroupPlan,
    GroupResult,
    ParsedBlock,
    ParsedOutput,
    ParseResult,
    Passed,
    Phase,
    ProjectedBlock,
    Skipped,
    SkipReason,
)
from .project import project
from .registry import (
    RegistryClosedError,
    RegistryCollisionError,
    RegistryError,
    RegistrySnapshot,
    build_registry,
)
from .runner import (
    DefaultExceptionPolicy,
    ExecExecutionProfile,
    ExecRuntime,
    PromptExecutionProfile,
    PromptRuntime,
    materialize,
    reset_globs,
    run_group,
)
from .settings import ParseSettings, ProjectionSettings, RunSettings

__all__ = [
    "BlockKind",
    "BlockResult",
    "CheckerFactory",
    "Contributor",
    "Counts",
    "DefaultExceptionPolicy",
    "Diagnostic",
    "DoctestDirective",
    "DocumentParser",
    "Errored",
    "ExampleRecipe",
    "ExceptionPolicy",
    "ExecExecutionProfile",
    "ExecRuntime",
    "ExecutionProfile",
    "ExecutionRuntime",
    "ExpectedOutput",
    "Failed",
    "Failure",
    "GroupPlan",
    "GroupResult",
    "MockTabDirective",
    "MystDocumentParser",
    "ParseResult",
    "ParseSettings",
    "ParsedBlock",
    "ParsedOutput",
    "Passed",
    "Phase",
    "ProjectedBlock",
    "ProjectionSettings",
    "PromptExecutionProfile",
    "PromptRuntime",
    "Provider",
    "Registrar",
    "Registration",
    "RegistryClosedError",
    "RegistryCollisionError",
    "RegistryError",
    "RegistrySnapshot",
    "RstDocumentParser",
    "RunSettings",
    "RuntimeOutcome",
    "RuntimeSettings",
    "SkipReason",
    "Skipped",
    "TestcleanupDirective",
    "TestcodeDirective",
    "TestoutputDirective",
    "TestsetupDirective",
    "build_registry",
    "ensure_directives_registered",
    "extract_blocks",
    "materialize",
    "parse_document",
    "project",
    "reset_globs",
    "run_group",
]
